background {
    monitor =
    path = /mnt/yourdrive/path/to/wallpaper.jpg
    blur_passes = 2
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(7aa2f7)
    inner_color = rgb(1a1b26)
    font_color = rgb(c0caf5)
    placeholder_text = password
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgb(c0caf5)
    font_size = 64
    position = 0, 100
    halign = center
    valign = center
}
